# Generated by Django 3.2.6 on 2022-01-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dw_commerce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=50)),
                ('district_code', models.CharField(max_length=50)),
                ('town', models.CharField(max_length=50)),
                ('town_code', models.CharField(max_length=50)),
                ('convenience', models.IntegerField()),
                ('c1_living_facility', models.IntegerField()),
                ('c2_living_facility', models.IntegerField()),
                ('sales_facility', models.IntegerField()),
                ('transportation_facility', models.IntegerField()),
                ('business_facilites', models.IntegerField()),
                ('accommodation_facility', models.IntegerField()),
                ('amusement_facility', models.IntegerField()),
                ('dst_facility', models.IntegerField()),
                ('automobile_facility', models.IntegerField()),
                ('etc', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='dw_fire_fighter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(max_length=50)),
                ('occupation_code', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('position_code', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('fire_station', models.CharField(max_length=50)),
                ('fire_station_code', models.CharField(max_length=50)),
                ('cnt_of_officers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='dw_fire_fighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fire_date', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('district_code', models.CharField(max_length=50)),
                ('fire_type', models.CharField(max_length=50)),
                ('type_code', models.CharField(max_length=50)),
                ('fire_source', models.CharField(max_length=50)),
                ('fire_source_code', models.CharField(max_length=50)),
                ('fire_factor', models.CharField(max_length=50)),
                ('fire_factor_code', models.CharField(max_length=50)),
                ('casualties', models.IntegerField()),
                ('dead', models.IntegerField()),
                ('injury', models.IntegerField()),
                ('property_damage', models.IntegerField()),
                ('place', models.CharField(max_length=50)),
                ('place_code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='dw_house',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('district_code', models.CharField(max_length=50)),
                ('town', models.CharField(max_length=50)),
                ('town_code', models.CharField(max_length=50)),
                ('sum', models.IntegerField()),
                ('house', models.IntegerField()),
                ('apartment', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='dw_humidity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('district_code', models.CharField(max_length=50)),
                ('humidity_date', models.CharField(max_length=50)),
                ('avg_humidity', models.IntegerField()),
                ('min_humidity', models.IntegerField()),
                ('max_humidity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='dw_public_facilites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=50)),
                ('district_code', models.CharField(max_length=50)),
                ('town', models.CharField(max_length=50)),
                ('town_code', models.CharField(max_length=50)),
                ('public_cnt', models.IntegerField()),
                ('cultural_facility', models.IntegerField()),
                ('religious_establishment', models.IntegerField()),
                ('medical_facility', models.IntegerField()),
                ('education_research_facility', models.IntegerField()),
                ('elderly_facility', models.IntegerField()),
                ('training_facility', models.IntegerField()),
                ('exercise_facility', models.IntegerField()),
                ('cemetery_related_facilities', models.IntegerField()),
                ('tourist_rest_facilities', models.IntegerField()),
                ('funeral_facility', models.IntegerField()),
                ('other_facilites', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='dw_temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('district_code', models.CharField(max_length=50)),
                ('temperature_date', models.CharField(max_length=50)),
                ('avg_temperature', models.IntegerField()),
                ('min_temperature', models.IntegerField()),
                ('max_temperature', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='dw_wind_velocity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('district_code', models.CharField(max_length=50)),
                ('wind_velocity_date', models.CharField(max_length=50)),
                ('avg_wind_velocity', models.IntegerField()),
                ('min_wind_velocity', models.IntegerField()),
                ('max_wind_velocity', models.IntegerField()),
            ],
        ),
    ]
