# Generated by Django 3.2.6 on 2022-01-04 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dw_merge_inner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=50)),
                ('district_code', models.CharField(max_length=50)),
                ('town', models.CharField(max_length=50)),
                ('town_code', models.CharField(max_length=50)),
                ('convenience', models.IntegerField()),
                ('c1_living_facility', models.IntegerField()),
                ('c2_living_facility', models.IntegerField()),
                ('sales_facility', models.IntegerField()),
                ('transportation_facility', models.IntegerField()),
                ('business_facilites', models.IntegerField()),
                ('accommodation_facility', models.IntegerField()),
                ('amusement_facility', models.IntegerField()),
                ('dst_facility', models.IntegerField()),
                ('automobile_facility', models.IntegerField()),
                ('etc', models.IntegerField()),
                ('cultural_facility', models.IntegerField()),
                ('religious_establishment', models.IntegerField()),
                ('medical_facility', models.IntegerField()),
                ('education_research_facility', models.IntegerField()),
                ('elderly_facility', models.IntegerField()),
                ('training_facility', models.IntegerField()),
                ('exercise_facility', models.IntegerField()),
                ('cemetery_related_facilities', models.IntegerField()),
                ('tourist_rest_facilities', models.IntegerField()),
                ('funeral_facility', models.IntegerField()),
                ('house', models.IntegerField()),
                ('apartment', models.IntegerField()),
            ],
        ),
    ]
